export const sidebarItems = [
	['How to use', '/how-to-use', []],
	['Compilacion QCH', '/compilacion-qch', []],
	['Plugins', '/plugins', []],
	['Standars', '/standars', []],
	['Components', '/components', []],
	['Auth Instalation', '/auth-instalation', []],
	['Auth Session', '/auth-session', []],
	['Auth User', '/auth-user', []],
	['Beyond UI', '/beyond-ui', []],
	['Essential UI', '/essential-ui', []],
	['Mailer', '/mailer', []],
	['Service Compilation B-E-P', '/compilation-backend', []],
	['Mobile Compilations', '/compilation-mobile', []],
	['Configure Git', '/configure-git', []],
	['Debug Mobiles Apps', '/debug-mobile-apps', []],
	['Running Bovino', '/running-bovino', []],
	['JView', '/jview', []],
	['Prettier Settings', '/prettier-settings', []],
	['How to install jadmin', '/how-to-install-jadmin', []],
	['Gmaps Integration', '/gmaps-integration', []],
	['Chart Component', '/chart-component', []],
	['React Types', '/react-types', []],
	['Deploy bg docs', '/deploy-bg-docs', []],
	['Implement Unit Test', '/implement-unit-test', []],
].sort();
